[DRAFT] depr: Remove EdxRestApiClient usage in edx-analytics-dashboard
raccoongang/edx-analytics-dashboard pull request #1
Opened 2022-04-04 14:40 UTC by UvgenGen

YouTrack: [OeX_Depr-30](https://youtrack.raccoongang.com/issue/OeX_Depr-30)
JIRA: [DEPR-131](https://openedx.atlassian.net/browse/DEPR-131)

2022-04-05 07:38 UTC, dyudyunov requested changes

2022-04-05 07:38 UTC, dyudyunov commented on common/clients.py
> +        response.raise_for_status()
👍

2022-04-05 07:38 UTC, dyudyunov commented on common/clients.py
> +                if response['pagination']['next']:
looks strange that responses differ
and is it possible to get KeyError here?

2022-04-05 07:38 UTC, dyudyunov commented on analytics_dashboard/courses/views/__init__.py
> +from edx_rest_api_client.exceptions import HttpClientError
This is actually a [Slumber error](https://github.com/openedx/edx-rest-api-client/blob/287e62a7a62874b1b2bbd8ac0a31308a19b78dec/edx_rest_api_client/exceptions.py#L3)

I'm suggesting replacing it with `from requests.exceptions import HTTPError`

2022-04-05 07:49 UTC, ruzniaievdm commented on analytics_dashboard/core/tests/test_utils.py
> +        self.assertEqual(client._timeout, (3.05, settings.LMS_DEFAULT_TIMEOUT))
may need to be imported `REQUEST_CONNECT_TIMEOUT` from `edx_rest_api_client`

2022-04-05 07:49 UTC, ruzniaievdm commented on analytics_dashboard/core/tests/test_utils.py
> +            timeout=(3.05, 4),
ditto

2022-04-05 17:08 UTC, idegtiarov requested changes
Please take a look at my comments inline.

2022-04-05 17:08 UTC, idegtiarov commented on analytics_dashboard/core/tests/test_utils.py
> +        self.assertEqual(client._timeout, (3.05, settings.LMS_DEFAULT_TIMEOUT))
+1 to @ruzniaievdm  comment. I would be interested default value also coming from the `settings` instead of directly from the module itself.

here and further

2022-04-05 17:08 UTC, idegtiarov commented on analytics_dashboard/core/utils.py
> +    def __init__(self, base_url, client_id, client_secret, timeout=(3.05, settings.LMS_DEFAULT_TIMEOUT)):
Since you are initializing the Client with the default param shouldn't it be added some default variable (type tuple probably) in our settings?

2022-04-05 17:08 UTC, idegtiarov commented on analytics_dashboard/courses/presenters/__init__.py
> +                f'{settings.COURSE_API_URL}blocks/',
Let's use `urljoin` from the `urllib.parse` so we could be confident that as a result, we would have a proper URL even if the setting has or has not had a trailing slash.

here and everywhere any URL is created

2022-04-05 17:08 UTC, idegtiarov commented on analytics_dashboard/courses/tests/test_views/__init__.py
> +            self.fail('httpretty is not enabled. The mock will not be used!')
Could you please clarify why we proceed with the method in case `httpretty` is not enabled and mock won't be used?

2022-04-05 17:08 UTC, idegtiarov commented on common/clients.py
> -    def __init__(self, url, access_token, timeout):
Why do we remove __init__ block? How custom timeout would be handled, just in case?

2022-04-05 17:08 UTC, idegtiarov commented on analytics_dashboard/courses/views/__init__.py
>                      course_details = response['results']
This L is not going to be working since the response is not a dict but the Response object.

2022-04-05 17:08 UTC, idegtiarov commented on common/clients.py
> +                response = self.get(
The exception handling error should be updated since we are with the OAuthClient from now.

2022-04-05 19:07 UTC, UvgenGen commented on analytics_dashboard/core/tests/test_utils.py
> +            timeout=(3.05, 4),
This test checks that explicit values are not equal to default ones, so i think we can leave it.

2022-04-05 19:45 UTC, UvgenGen commented on common/clients.py
> -    def __init__(self, url, access_token, timeout):
OAuthAPIClient expect this params:
https://github.com/openedx/edx-rest-api-client/blob/master/edx_rest_api_client/client.py#L215
so I think we don't need additional handling for timeout.

2022-04-06 12:30 UTC, UvgenGen commented on analytics_dashboard/courses/tests/test_views/__init__.py
> +            self.fail('httpretty is not enabled. The mock will not be used!')
This proceed in cases when method used in tests without adding `@httpretty.activate` decorator.
Same as in `mock_course_api` method: https://github.com/raccoongang/edx-analytics-dashboard/pull/1/files#diff-486cc1ddd42a61f5dcd6f6a8ac48af538de1f17867a621e06fc907a07bbc7379R53

2022-04-06 12:31 UTC, idegtiarov requested changes

2022-04-06 12:31 UTC, idegtiarov commented on analytics_dashboard/core/tests/test_utils.py
> +            timeout=(3.05, 4),
3.05 is the default REQUEST_CONNECT_TIMEOUT value could we use it until we do not change the default behavior?

2022-04-06 12:33 UTC, UvgenGen commented on analytics_dashboard/courses/views/__init__.py
>                      course_details = response['results']
updated

2022-04-06 16:46 UTC, UvgenGen commented on common/clients.py
> +                if response['pagination']['next']:
added handling for KeyError

2022-04-06 16:47 UTC, UvgenGen commented on analytics_dashboard/courses/views/__init__.py
> +from edx_rest_api_client.exceptions import HttpClientError
updated

2022-04-06 16:47 UTC, UvgenGen commented on analytics_dashboard/core/tests/test_utils.py
> +        self.assertEqual(client._timeout, (3.05, settings.LMS_DEFAULT_TIMEOUT))
updated

2022-04-06 16:52 UTC, UvgenGen commented on analytics_dashboard/core/tests/test_utils.py
> +            timeout=(3.05, 4),
I changed this value to  2.05 for this test.

2022-04-06 16:53 UTC, UvgenGen commented on analytics_dashboard/core/utils.py
> +    def __init__(self, base_url, client_id, client_secret, timeout=(3.05, settings.LMS_DEFAULT_TIMEOUT)):
updated

2022-04-06 16:53 UTC, UvgenGen commented on analytics_dashboard/courses/presenters/__init__.py
> +                f'{settings.COURSE_API_URL}blocks/',
done

2022-04-07 11:56 UTC, closed without merging